# Generated by Django 3.0.6 on 2020-07-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200705_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newaccountdata',
            name='Home_Address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
